// src/lib/levelsData.ts
import { LevelConfig } from './types';

export const LEVELS: LevelConfig[] = [
  // --- ZONA 1: PESISIR SOLARIA (Dasar Sekuensial & Belokan) ---
  {
    id: 1,
    zone: "Zona 1: Pesisir Solaria",
    title: "Misi 1: Langkah Perdana",
    gridSize: 6,
    startPos: { x: 1, y: 4 },
    startDirection: 'UP',
    targetPos: { x: 1, y: 1 },
    targetType: 'BATTERY',
    targetDescription: "Kapsul Baterai Surya",
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Baterai ARKA melemah! Pandu ARKA melangkah 3 petak lurus ke depan untuk mengisi energi.",
    optimalBlocks: 3
  },
  {
    id: 2,
    zone: "Zona 1: Pesisir Solaria",
    title: "Misi 2: Tikungan Pesisir",
    gridSize: 6,
    startPos: { x: 1, y: 4 },
    startDirection: 'UP',
    targetPos: { x: 4, y: 1 },
    targetType: 'MANGROVE',
    targetDescription: "Bibit Mangrove Pasir",
    obstacles: [{ x: 1, y: 2 }, { x: 2, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Batang pohon tumbang menghalangi jalan lurus. Belokkan ARKA memutari pohon menuju bibit!",
    optimalBlocks: 6
  },
  {
    id: 3,
    zone: "Zona 1: Pesisir Solaria",
    title: "Misi 3: Celah Karang",
    gridSize: 6,
    startPos: { x: 0, y: 5 },
    startDirection: 'UP',
    targetPos: { x: 3, y: 2 },
    targetType: 'WATER_PUMP',
    targetDescription: "Katup Pompa Pantai",
    obstacles: [{ x: 0, y: 3 }, { x: 1, y: 3 }, { x: 2, y: 3 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Dinding karang membentang horizontal. Cari celah di sebelah kanan untuk melewatinya.",
    optimalBlocks: 7
  },
  {
    id: 4,
    zone: "Zona 1: Pesisir Solaria",
    title: "Misi 4: Pola Zig-Zag",
    gridSize: 6,
    startPos: { x: 4, y: 5 },
    startDirection: 'LEFT',
    targetPos: { x: 1, y: 0 },
    targetType: 'BATTERY',
    targetDescription: "Baterai Cadangan Karang",
    obstacles: [{ x: 2, y: 4 }, { x: 3, y: 2 }, { x: 1, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Batu karang tersebar acak. Rancang pola langkah zig-zag yang efisien.",
    optimalBlocks: 8
  },
  {
    id: 5,
    zone: "Zona 1: Pesisir Solaria",
    title: "Misi 5: Ujian Pesisir",
    gridSize: 6,
    startPos: { x: 0, y: 5 },
    startDirection: 'RIGHT',
    targetPos: { x: 5, y: 0 },
    targetType: 'SOLAR_CORE',
    targetDescription: "Menara Relai Pantai",
    obstacles: [{ x: 2, y: 5 }, { x: 2, y: 3 }, { x: 2, y: 1 }, { x: 4, y: 4 }, { x: 4, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Selesaikan navigasi melintasi seluruh pantai menuju Menara Relai!",
    optimalBlocks: 10
  },

  // --- ZONA 2: HUTAN MANGROVE (Labirin & Rintangan Padat) ---
  {
    id: 6,
    zone: "Zona 2: Hutan Mangrove",
    title: "Misi 6: Gerbang Rawa Bakau",
    gridSize: 6,
    startPos: { x: 2, y: 5 },
    startDirection: 'UP',
    targetPos: { x: 2, y: 0 },
    targetType: 'MANGROVE',
    targetDescription: "Bibit Bakau Sejati",
    obstacles: [{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 3, y: 3 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Jalur tengah tertutup rapat oleh akar bakau raksasa. Manfaatkan jalur sisi luar.",
    optimalBlocks: 9
  },
  {
    id: 7,
    zone: "Zona 2: Hutan Mangrove",
    title: "Misi 7: Koridor Sempit",
    gridSize: 6,
    startPos: { x: 5, y: 5 },
    startDirection: 'UP',
    targetPos: { x: 0, y: 1 },
    targetType: 'WATER_PUMP',
    targetDescription: "Generator Air Asin",
    obstacles: [{ x: 4, y: 4 }, { x: 3, y: 3 }, { x: 2, y: 2 }, { x: 1, y: 1 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Akar pohon membentuk garis diagonal. Ikuti alur koridor tanpa membentur.",
    optimalBlocks: 9
  },
  {
    id: 8,
    zone: "Zona 2: Hutan Mangrove",
    title: "Misi 8: Kantung Lumpur",
    gridSize: 6,
    startPos: { x: 1, y: 5 },
    startDirection: 'UP',
    targetPos: { x: 4, y: 3 },
    targetType: 'BATTERY',
    targetDescription: "Baterai Terapung",
    obstacles: [{ x: 1, y: 3 }, { x: 2, y: 3 }, { x: 4, y: 4 }, { x: 3, y: 1 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Jangan terburu-buru belok! Periksa posisi target yang berada di celah sempit.",
    optimalBlocks: 7
  },
  {
    id: 9,
    zone: "Zona 2: Hutan Mangrove",
    title: "Misi 9: Lingkaran Akar",
    gridSize: 7,
    startPos: { x: 0, y: 6 },
    startDirection: 'RIGHT',
    targetPos: { x: 3, y: 3 },
    targetType: 'MANGROVE',
    targetDescription: "Pohon Lindur Tua",
    obstacles: [{ x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 }, { x: 2, y: 4 }, { x: 4, y: 4 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Pohon Lindur dilindungi benteng akar keliling. Masuklah lewat gerbang selatan!",
    optimalBlocks: 8
  },
  {
    id: 10,
    zone: "Zona 2: Hutan Mangrove",
    title: "Misi 10: Inti Rawa Solaria",
    gridSize: 7,
    startPos: { x: 6, y: 6 },
    startDirection: 'UP',
    targetPos: { x: 0, y: 0 },
    targetType: 'SOLAR_CORE',
    targetDescription: "Kristal Rawa Hijau",
    obstacles: [{ x: 5, y: 4 }, { x: 4, y: 2 }, { x: 2, y: 4 }, { x: 3, y: 5 }, { x: 1, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT'],
    storyPrompt: "Tantangan akhir Zona 2! Jelajahi labirin rawa terbesar dan pulihkan Kristal Rawa.",
    optimalBlocks: 14
  },

  // --- ZONA 3: LEMBAH GEISER (Gerakan Khusus & Skill Lompat) ---
  {
    id: 11,
    zone: "Zona 3: Lembah Geiser",
    title: "Misi 11: Retakan Batuan",
    gridSize: 6,
    startPos: { x: 1, y: 4 },
    startDirection: 'UP',
    targetPos: { x: 1, y: 1 },
    targetType: 'BATTERY',
    targetDescription: "Kapsul Panas Bumi",
    obstacles: [{ x: 1, y: 3 }, { x: 2, y: 3 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD'],
    storyPrompt: "Ada retakan tanah setinggi 1 petak di depanmu! Gunakan balok Lompat untuk melompatinya.",
    optimalBlocks: 2
  },
  {
    id: 12,
    zone: "Zona 3: Lembah Geiser",
    title: "Misi 12: Lompatan Ganda",
    gridSize: 6,
    startPos: { x: 0, y: 5 },
    startDirection: 'RIGHT',
    targetPos: { x: 5, y: 5 },
    targetType: 'WATER_PUMP',
    targetDescription: "Kran Air Panas",
    obstacles: [{ x: 2, y: 5 }, { x: 4, y: 5 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD'],
    storyPrompt: "Dua lubang uap panas berbaris lurus! Kombinasikan langkah biasa dan lompatan presisi.",
    optimalBlocks: 4
  },
  {
    id: 13,
    zone: "Zona 3: Lembah Geiser",
    title: "Misi 13: Labirin Lava Dingin",
    gridSize: 6,
    startPos: { x: 5, y: 0 },
    startDirection: 'DOWN',
    targetPos: { x: 0, y: 5 },
    targetType: 'MANGROVE',
    targetDescription: "Lumut Vulkanik",
    obstacles: [{ x: 4, y: 2 }, { x: 3, y: 2 }, { x: 2, y: 4 }, { x: 1, y: 4 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD'],
    storyPrompt: "Pilih strategimu: melompati rintangan atau memutarinya lewat sisi aman?",
    optimalBlocks: 9
  },
  {
    id: 14,
    zone: "Zona 3: Lembah Geiser",
    title: "Misi 14: Kawah Bertingkat",
    gridSize: 7,
    startPos: { x: 1, y: 6 },
    startDirection: 'UP',
    targetPos: { x: 5, y: 2 },
    targetType: 'BATTERY',
    targetDescription: "Generator Termal",
    obstacles: [{ x: 1, y: 4 }, { x: 3, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 5 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD'],
    storyPrompt: "Gunakan kemampuan analisis spasialmu untuk mendaki dinding kawah.",
    optimalBlocks: 8
  },
  {
    id: 15,
    zone: "Zona 3: Lembah Geiser",
    title: "Misi 15: Jantung Magma",
    gridSize: 7,
    startPos: { x: 0, y: 3 },
    startDirection: 'RIGHT',
    targetPos: { x: 6, y: 3 },
    targetType: 'SOLAR_CORE',
    targetDescription: "Inti Vulkanik Solaria",
    obstacles: [{ x: 2, y: 3 }, { x: 4, y: 3 }, { x: 3, y: 2 }, { x: 3, y: 4 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD'],
    storyPrompt: "Lompat menembus semburan uap dan aktifkan Inti Vulkanik!",
    optimalBlocks: 6
  },

  // --- ZONA 4: REAKTOR SURYA (Algoritma Efisien & Looping) ---
  {
    id: 16,
    zone: "Zona 4: Reaktor Surya",
    title: "Misi 16: Jalur Lurus Panjang",
    gridSize: 7,
    startPos: { x: 0, y: 3 },
    startDirection: 'RIGHT',
    targetPos: { x: 6, y: 3 },
    targetType: 'BATTERY',
    targetDescription: "Kabel Transmisi Utama",
    obstacles: [{ x: 3, y: 2 }, { x: 3, y: 4 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT_2X'],
    storyPrompt: "Jaraknya sangat jauh (6 petak)! Gunakan balok 'Ulangi 2x' agar hemat balok perintah.",
    optimalBlocks: 4
  },
  {
    id: 17,
    zone: "Zona 4: Reaktor Surya",
    title: "Misi 17: Tangga Algoritma",
    gridSize: 7,
    startPos: { x: 1, y: 5 },
    startDirection: 'UP',
    targetPos: { x: 5, y: 1 },
    targetType: 'WATER_PUMP',
    targetDescription: "Pendingin Reaktor",
    obstacles: [{ x: 1, y: 3 }, { x: 3, y: 3 }, { x: 3, y: 1 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT_2X'],
    storyPrompt: "Susun pola tangga berulang: (Maju - Belok Kanan - Maju - Belok Kiri).",
    optimalBlocks: 8
  },
  {
    id: 18,
    zone: "Zona 4: Reaktor Surya",
    title: "Misi 18: Barisan Sel Surya",
    gridSize: 7,
    startPos: { x: 0, y: 6 },
    startDirection: 'UP',
    targetPos: { x: 6, y: 0 },
    targetType: 'BATTERY',
    targetDescription: "Panel Fotovoltaik Induk",
    obstacles: [{ x: 2, y: 6 }, { x: 2, y: 5 }, { x: 4, y: 2 }, { x: 4, y: 1 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT_2X'],
    storyPrompt: "Optimalkan gerakanmu di antara deretan sel surya yang sedang mengisi daya.",
    optimalBlocks: 10
  },
  {
    id: 19,
    zone: "Zona 4: Reaktor Surya",
    title: "Misi 19: Spiral Konsentris",
    gridSize: 7,
    startPos: { x: 0, y: 0 },
    startDirection: 'RIGHT',
    targetPos: { x: 3, y: 3 },
    targetType: 'MANGROVE',
    targetDescription: "Kebun Bioreaktor",
    obstacles: [
      { x: 1, y: 1 }, { x: 2, y: 1 }, { x: 3, y: 1 }, { x: 4, y: 1 }, { x: 5, y: 1 },
      { x: 5, y: 2 }, { x: 5, y: 3 }, { x: 5, y: 4 }, { x: 5, y: 5 },
      { x: 1, y: 5 }, { x: 2, y: 5 }, { x: 3, y: 5 }, { x: 4, y: 5 }
    ],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT_2X'],
    storyPrompt: "Ikuti jalur spiral obat nyamuk menuju pusat bioreaktor di tengah pulau!",
    optimalBlocks: 12
  },
  {
    id: 20,
    zone: "Zona 4: Reaktor Surya",
    title: "Misi 20: Saklar Reaktor Raya",
    gridSize: 8,
    startPos: { x: 1, y: 7 },
    startDirection: 'UP',
    targetPos: { x: 6, y: 1 },
    targetType: 'SOLAR_CORE',
    targetDescription: "Kubah Reaktor Fotonik",
    obstacles: [{ x: 3, y: 6 }, { x: 3, y: 4 }, { x: 5, y: 4 }, { x: 2, y: 2 }, { x: 4, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'REPEAT_2X', 'JUMP_FORWARD'],
    storyPrompt: "Aktifkan seluruh generator pendingin untuk membuka gerbang kubah fotonik!",
    optimalBlocks: 11
  },

  // --- ZONA 5: PUNCAK OBSERVATORIUM (Master Algoritma Kompleks) ---
  {
    id: 21,
    zone: "Zona 5: Puncak Observatorium",
    title: "Misi 21: Tangga Menuju Awan",
    gridSize: 8,
    startPos: { x: 0, y: 7 },
    startDirection: 'UP',
    targetPos: { x: 7, y: 0 },
    targetType: 'BATTERY',
    targetDescription: "Baterai Ion Stratosfer",
    obstacles: [{ x: 1, y: 6 }, { x: 2, y: 5 }, { x: 3, y: 4 }, { x: 4, y: 3 }, { x: 5, y: 2 }, { x: 6, y: 1 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD', 'REPEAT_2X'],
    storyPrompt: "Tembok diagonal sempurna membelah pulau! Lompat menembus retakan diagonal.",
    optimalBlocks: 12
  },
  {
    id: 22,
    zone: "Zona 5: Puncak Observatorium",
    title: "Misi 22: Medan Cermin Teleskop",
    gridSize: 8,
    startPos: { x: 7, y: 7 },
    startDirection: 'LEFT',
    targetPos: { x: 1, y: 1 },
    targetType: 'WATER_PUMP',
    targetDescription: "Pompa Pendingin Optik",
    obstacles: [{ x: 5, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 4 }, { x: 2, y: 3 }, { x: 4, y: 2 }],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD', 'REPEAT_2X'],
    storyPrompt: "Cermin pantul raksasa menghalangi jalan. Rencanakan rute terpendek tanpa tersesat.",
    optimalBlocks: 10
  },
  {
    id: 23,
    zone: "Zona 5: Puncak Observatorium",
    title: "Misi 23: Labirin Kristal Bintang",
    gridSize: 8,
    startPos: { x: 0, y: 4 },
    startDirection: 'RIGHT',
    targetPos: { x: 7, y: 4 },
    targetType: 'MANGROVE',
    targetDescription: "Pohon Aurora Abadi",
    obstacles: [
      { x: 2, y: 3 }, { x: 2, y: 4 }, { x: 2, y: 5 },
      { x: 5, y: 3 }, { x: 5, y: 4 }, { x: 5, y: 5 },
      { x: 3, y: 1 }, { x: 4, y: 7 }
    ],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD', 'REPEAT_2X'],
    storyPrompt: "Pohon Aurora dijaga dua gerbang pilar ganda. Lewati pilar dengan lompatan atau manuver.",
    optimalBlocks: 9
  },
  {
    id: 24,
    zone: "Zona 5: Puncak Observatorium",
    title: "Misi 24: Titik Nadir Solaria",
    gridSize: 8,
    startPos: { x: 2, y: 7 },
    startDirection: 'UP',
    targetPos: { x: 5, y: 0 },
    targetType: 'BATTERY',
    targetDescription: "Baterai Inti Antariksa",
    obstacles: [
      { x: 1, y: 5 }, { x: 3, y: 5 }, { x: 4, y: 5 }, { x: 6, y: 5 },
      { x: 2, y: 3 }, { x: 5, y: 3 }, { x: 3, y: 1 }, { x: 4, y: 1 }
    ],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD', 'REPEAT_2X'],
    storyPrompt: "Dua baris barikade menghadang. Temukan simetri jalur algoritma terbaik!",
    optimalBlocks: 11
  },
  {
    id: 25,
    zone: "Zona 5: Puncak Observatorium",
    title: "Misi 25: Restorasi Sempurna Solaria",
    gridSize: 8,
    startPos: { x: 0, y: 7 },
    startDirection: 'UP',
    targetPos: { x: 7, y: 0 },
    targetType: 'SOLAR_CORE',
    targetDescription: "Mercusuar Agung Solaria",
    obstacles: [
      { x: 1, y: 6 }, { x: 3, y: 6 }, { x: 5, y: 6 },
      { x: 2, y: 4 }, { x: 4, y: 4 }, { x: 6, y: 4 },
      { x: 1, y: 2 }, { x: 3, y: 2 }, { x: 5, y: 2 }
    ],
    availableBlocks: ['MOVE_FORWARD', 'TURN_RIGHT', 'TURN_LEFT', 'JUMP_FORWARD', 'REPEAT_2X'],
    storyPrompt: "Ujian Terakhir Sang Insinyur! Padukan seluruh keahlian komputasimu untuk menyalakan Mercusuar Agung!",
    optimalBlocks: 15
  }
];